### 
Business Problem    * 
• There is historical data of insurance claim cases (around 1,300+ case    s).
• Each case involves bodily injury insurance claims from a specific re
    g    ion.
• Some claimants hire an attorney, some d
    o     not.
• Hiring an attorney usually increases the settlement amount, which a
    f    fects:
   ○ The cost to the insurance     company
   ○ The profitability of th
       e     insurer
• The insurance company
         wants to:
   ○ Predict the likelihood that a claimant will hire a    n attorney
   ○ Understand which types of customers are more lik
       e    ly to do so
• Based on this, the compa    ny wants to:
   ○ Design be    tter policies
   ○ Target different customer segme
       nts differently#### 
B    usiness Problem    :
Attorney hiring increases settlement amount
         ### Business Understandingcompany cos    t    .

Object    ive:
Predict whether claimant will hire atto    r    ney.

ML P    roblem:
Binary classi        Target variable: Attorney_Hired            
Possible values            :
1 = Y            es
0 =             Nof    ication

Busin            ess     Questions:
1. Who is likely to             hir    e attorney?
2. Which regions have high             atto    rney hiring?
3. What factors influence att    o    rney hiring?

B    usiness Action:
1. Improve claim h    andling strategy
2. Better     reserve planning
3. Cus    tomer segmentation
4. Cost reduction

# Import Necessary Libraries

In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,roc_auc_score,precision_score
from pickle import dump

# Import Data

In [3]:
claimants_data=pd.read_csv("Claimant.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

# Data Understanding

In [4]:
claimants_data.shape

(1340, 7)

In [5]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [6]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [7]:
claimants_data.duplicated().sum()

0

# 4. Data Preparation

## 4.1 Data Cleaning

In [8]:
claimants_data.dropna(inplace= True) #istead of giving new variable name we can use inplace = true which directly impact on the orginal data

In [9]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [10]:
claimants_data.shape

(1096, 7)

## 4.2 Seperate input and output

In [11]:
X =claimants_data.drop(labels=["CASENUM","ATTORNEY"],axis=1 )
X

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [12]:
y= claimants_data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

# 5. Model Building

#### also understand the below output the blocks follows like X_train,X_test,Y_train,Y_test

In [13]:
 X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20,shuffle=True,random_state=36) 
# test_size or train_size either one is enough
# since we have given shuffle so each time we run it shuffles which change the outcome percentage so to keep the first shuffle as it is we use RANDOM_STATE which can be given any positive integer

In [14]:
X_train

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
42       1.0       1.0       0.0    46.0   8.090
305      0.0       1.0       0.0    33.0   0.886
828      0.0       1.0       0.0    30.0   6.967
1324     0.0       1.0       0.0    10.0   6.564
1317     0.0       1.0       0.0     7.0   3.535
...      ...       ...       ...     ...     ...
1204     1.0       1.0       0.0     6.0   3.780
1140     1.0       1.0       0.0    30.0   1.000
1129     0.0       1.0       0.0    10.0   0.100
741      1.0       1.0       0.0    30.0   5.010
787      0.0       1.0       0.0    50.0  51.146

[876 rows x 5 columns]

# 6. Model Training

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
logistic_model=LogisticRegression()
logistic_model

LogisticRegression()

In [17]:
logistic_model.fit(X_train,y_train)

LogisticRegression()

In [18]:
dt_model=DecisionTreeClassifier()

In [19]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(estimator  = dt_model,param_grid = {"max_depth":[5,6,7,8,9,10],
                                                                    "criterion":['gini','entropy'],
                                                                    "n_estimators":[50,75,100,150]})
grid_search.fit(X,y)

print(grid_search.best_params_)
print(grid_search.best_score_)

ValueError: Invalid parameter 'n_estimators' for estimator DecisionTreeClassifier(max_depth=5). Valid parameters are: ['ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'random_state', 'splitter'].

# 7. Model Testing

## 7.1 Training Data

In [ ]:
y_pred_train=dt_model.predict(X_train) #return the output (y)
y_pred_train

## 7.2 Test Data

In [ ]:
y_pred_test=dt_model.predict(X_test) #return the output (y)
y_pred_test

# 8. Model Evaluation

## 8.1 Training data evaluation metrics

In [ ]:
print(classification_report(y_train,y_pred_train))

In [ ]:
print(confusion_matrix(y_train,y_pred_train))

### ROC Curve - Receiver Operating Characteristics
### AUC - Area under this curve

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score #fpr- false positive rate , tpr - true positive rate
fpr,tpr, thresholds=roc_curve(y_train,dt_model.predict_proba (X_train)[:,1])

auc=roc_auc_score(y_train,y_pred_train)
print(auc)
import matplotlib.pyplot as plt

plt.plot(fpr, tpr, color='red', label='logit model ( area = %0.2f)' % auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or (1 - True Negative Rate)')
plt.ylabel('True Positive Rate')

## 8.2 Test data evaluation metrics

In [ ]:
accuracy_score(y_test,y_pred_test)

In [ ]:
print(confusion_matrix(y_test,y_pred_test))

In [ ]:
print(classification_report(y_test,y_pred_test))

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score #fpr- false positive rate , tpr - true positive rate
fpr,tpr, thresholds=roc_curve(y_test,dt_model.predict_proba (X_test)[:,1])

auc=roc_auc_score(y_test,y_pred_test)
print(auc)
import matplotlib.pyplot as plt

plt.plot(fpr, tpr, color='red', label='logit model ( area = %0.2f)' % auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or (1 - True Negative Rate)')
plt.ylabel('True Positive Rate')

#  Overfitting problem: Hey, this model got overfitted
## Point to Note: We always expect GENERALIZED model

# Bias variant

Bias : always associated With training data

Variance Always associated with test data

In [ ]:
dt_model_bias=DecisionTreeClassifier(max_depth= 5)

In [ ]:
dt_model_bias.fit(X_train,y_train)

In [ ]:
from sklearn.tree import plot_tree

In [ ]:
plt.figure(figsize= (8,10))
plot_tree(decision_tree=dt_model_bias,fontsize=7,filled=True)

plt.show()

In [ ]:
y_pred_train=dt_model.predict(X_train) #return the output (y)
y_pred_train

In [ ]:
y_pred_test=dt_model.predict(X_test) #return the output (y)
y_pred_test

In [ ]:
print(classification_report(y_train,y_pred_train))

In [ ]:
print(confusion_matrix(y_train,y_pred_train))

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score #fpr- false positive rate , tpr - true positive rate
fpr,tpr, thresholds=roc_curve(y_train,dt_model_bias.predict_proba (X_train)[:,1])

auc=roc_auc_score(y_train,y_pred_train)
print(auc)
import matplotlib.pyplot as plt

plt.plot(fpr, tpr, color='red', label='logit model ( area = %0.2f)' % auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or (1 - True Negative Rate)')
plt.ylabel('True Positive Rate')

In [ ]:
print(classification_report(y_test,y_pred_test))

In [ ]:
print(confusion_matrix(y_test,y_pred_test))

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score #fpr- false positive rate , tpr - true positive rate
fpr,tpr, thresholds=roc_curve(y_test,dt_model_bias.predict_proba (X_test)[:,1])

auc=roc_auc_score(y_test,y_pred_test)
print(auc)
import matplotlib.pyplot as plt

plt.plot(fpr, tpr, color='red', label='logit model ( area = %0.2f)' % auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or (1 - True Negative Rate)')
plt.ylabel('True Positive Rate')

# 9. Model Deployment

In [ ]:
from pickle import dump

In [ ]:
dump(logistic_model,open("Claimant_decision_metrics.pkl","wb"))

# THE END !!

# Now decision is changed to generalized from overfitting after using Bias variance

# Hper paramtric model
## Grid Search CV: use to find which is best mx depth value , metric , creatia