### 
Business Problem    * 
• There is historical data of insurance claim cases (around 1,300+ case    s).
• Each case involves bodily injury insurance claims from a specific re
    g    ion.
• Some claimants hire an attorney, some d
    o     not.
• Hiring an attorney usually increases the settlement amount, which a
    f    fects:
   ○ The cost to the insurance     company
   ○ The profitability of th
       e     insurer
• The insurance company
         wants to:
   ○ Predict the likelihood that a claimant will hire a    n attorney
   ○ Understand which types of customers are more lik
       e    ly to do so
• Based on this, the compa    ny wants to:
   ○ Design be    tter policies
   ○ Target different customer segme
       nts differently#### 
B    usiness Problem    :
Attorney hiring increases settlement amount
         ### Business Understandingcompany cos    t    .

Object    ive:
Predict whether claimant will hire atto    r    ney.

ML P    roblem:
Binary classi        Target variable: Attorney_Hired            
Possible values            :
1 = Y            es
0 =             Nof    ication

Busin            ess     Questions:
1. Who is likely to             hir    e attorney?
2. Which regions have high             atto    rney hiring?
3. What factors influence att    o    rney hiring?

B    usiness Action:
1. Improve claim h    andling strategy
2. Better     reserve planning
3. Cus    tomer segmentation
4. Cost reduction

# Import Necessary Libraries

In [28]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Import Data

In [2]:
claimants_data=pd.read_csv("Claimant.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

# Data Understanding

In [3]:
claimants_data.shape

(1340, 7)

In [8]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [15]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [9]:
claimants_data.duplicated().sum()

0

# 4. Data Preparation

## 4.1 Data Cleaning

In [19]:
claimants_data.dropna(inplace= True) #istead of giving new variable name we can use inplace = true which directly impact on the orginal data

In [20]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [22]:
claimants_data.shape

(1096, 7)

## 4.2 Seperate input and output

In [24]:
X =claimants_data.drop(labels=["CASENUM","ATTORNEY"],axis=1 )
X

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [38]:
y= claimants_data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

# 5. Model Building

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [45]:
logistic_model=LogisticRegression()
logistic_model

LogisticRegression()

# 6. Model Training

In [46]:
logistic_model.fit(X,y)

LogisticRegression()

In [47]:
logistic_model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

# 7. Model Testing

In [55]:
y_predict=logistic_model.predict(X) #return the output (y)
y_predict

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

# 8. Model Evaluation

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
accuracy_score(y,y_predict)

0.708029197080292

# 9. Model Deployment

In [59]:
from pickle import dump

In [60]:
dump(logistic_model,open("Claimant.pkl","wb"))

# THE END !!